[build-system]
requires = ["setuptools", "oldest-supported-numpy"]
build_backend = "setuptools.build_meta"

[project]
name = "nuflux"
version = "2.0.3"
description = "A library for calculating atmospheric neutrino fluxes"
readme = "README.md"
#requires_python = "~=3.8"
dependencies = ['numpy']
license = {file = "LICENCE"}
keywords = ["python", "science", "astronomy", "astrophysics", "IceCube", "atmospheric", "neutrino"]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: C++',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Topic :: Scientific/Engineering :: Astronomy',
    'Topic :: Scientific/Engineering :: Physics',
    ]

[tool.setuptools]
packages = ['nuflux']